set lines=60 columns=180              " 2 panes wide
set guioptions-=m                     " hide file/edit/etc. menu
set guioptions-=T                     " hide stupid button bar

if has('gui_macvim')

else
  set guifont="Hack 11"

  cnoremap <S-Insert> <MiddleMouse>

endif
