#!/bin/bash

# Color directory
CD="$HOME/.Xresources"

# Fetch the Colors
BG=$(grep -i "define bg" ${CD} | cut -d' ' -f 3)
FG=$(grep -i "define fg" ${CD} | cut -d' ' -f 3)

BLACK=$(grep -i "define blk" ${CD} | cut -d' ' -f 3)
RED=$(grep -i "define red" ${CD} | cut -d' ' -f 3)
GREEN=$(grep -i "define grn" ${CD} | cut -d' ' -f 3)
YELLOW=$(grep -i "define ylw" ${CD} | cut -d' ' -f 3)
BLUE=$(grep -i "define blu" ${CD} | cut -d' ' -f 3)
MAGENTA=$(grep -i "define mag" ${CD} | cut -d' ' -f 3)
CYAN=$(grep -i "define cyn" ${CD} | cut -d' ' -f 3)
WHITE=$(grep -i "define wht" ${CD} | cut -d' ' -f 3)

# Fonts
FONT1="-gohu-gohufont-medium-r-normal--11-80-100-100-c-60-iso8859-1"
FONT2="-lucy-tewi-medium-r-normal--11-90-75-75-p-58-iso10646-1"
FONT3="-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"
FONT4="-benis-lemon-medium-r-normal--10-110-75-75-m-50-iso8859-1"
FONT5="-nil-profont-medium-r-normal--10-110-72-72-c-60-iso8859-1"
FONT6="-kakwa-kakwafont-medium-r-normal--12-120-72-72-c-60-iso8859-1"

#Actions
VOLT="pamixer --toggle-mute"
VOLU="pamixer --increase 5"
VOLD="pamixer --decrease 5"
TMUS="mpc toggle"
NMUS="mpc next"
POW="~/.config/panel/bar_pop"

# Functions

#Workspace number

ws(){
  ws=$(i3-msg -t get_outputs | sed 's/.*"current_workspace":"\([^"]*\)".*/\1/')
  echo "%{F$RED}${ws}"
}

music() {
  music=$(n=$(mpc current); if [ -z "$n" ] ; then echo; else echo " $n"; fi)
  echo "%{F$GREEN}${music}"
}

cpu(){
  cpu=$(mpstat -P ALL 1 1 | awk '(NR>11) {print $3+$5}' | paste -d " " - - - -)
  echo "%{F$YELLOW} ${cpu}"
}

net(){
  ipnet=$(ip=$(/sbin/ifconfig | grep eth0 -A 5 | sed '/inet addr:/!d;s/.*addr:\([0-9.]*\).*/\1/'); if [ ! -z "$ip" ]; then echo "$ip"; else echo "No Connection";fi)
  ip=$(ip=$(/sbin/ifconfig | grep wlan0 -A 5 | sed '/inet\ addr/!d;s/.*addr:\([0-9.]*\).*/\1/'); if [ ! -z $ip ]; then echo $ip ;else ip=$(/sbin/ifconfig | grep eth0 -A 5 | sed '/inet addr:/!d;s/.*addr:\([0-9.]*\).*/\1/'); if [ ! -z "$ip" ]; then echo "$ip"; else echo "No ip";fi;fi)
  ping=$(pn=$(timeout .8 ping 185.40.64.65 -c 1 -s 24 | sed '2!d;s/.*time=\([0-9]*\).*/\1/'); if [ -z $pn ] ; then echo "No Connection"; else echo "${pn}ms"; fi)
  echo "%{F$GREEN} ${ip}   ${ping}"
}

ram(){
  ram=$(free -h | awk '/\-\/+/ {print $3}')
  echo "%{F$YELLOW} ${ram}"
}

temp(){
  temp=$(sensors | grep temp1 | sed '1d;s/.*+\([0-9]*\).*/\1/')
  echo "%{F$YELLOW} ${temp}C"
}

clock(){
  clock=$(date "+%d %b %Y  %H:%M")
  echo "%{F$RED}${clock}"
}

vol(){
  vol=$(pamixer --get-volume)
  echo "%{F$YELLOW} ${vol}"
}

pow(){
  FOLD="/sys/class/power_supply"
  val=$(if [ -d $FOLD/BAT0 ]; then cat $FOLD/BAT0/capacity; fi)
  pow=$(if [ $(cat $FOLD/AC0/online) = 1 ]; then if [ ! -d $FOLD/BAT0 ]; then echo ""; else echo "";fi; else if [[ $val < 12 ]]; then echo ""; else if [[ $val > 90 ]]; then echo ""; else echo "";fi; fi;fi)
  echo "%{F$YELLOW}${pow}"
}

while :; do
  echo "   $(ws)  %{A1:$TMUS:}%{A3:$NMUS:}$(music)%{A}%{A}%{c}$(cpu)   $(temp)   $(ram) %{r}$(net)  %{A:$VOLT:}%{A4:$VOLU:}%{A5:$VOLD:}$(vol) %{A}%{A}%{A}  $(clock) %{A:$POW:}   %{A} "
  sleep .5
done | lemonbar -g "x14" -f "$FONT3" -f "$FONT5"  -B "$BG" -F "$FG" -p -d  | \
  while :; do read line; eval $line; done &
